/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TPass extends Token
{
    public TPass()
    {
        super.setText("passo");
    }

    public TPass(int line, int pos)
    {
        super.setText("passo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPass(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPass(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPass text.");
    }
}
