/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpOp3ExpExpLogica4 extends PExpLogica4
{
    private PExp _pre_;
    private POp3 _op3_;
    private PVarValue _varValue_;

    public AExpOp3ExpExpLogica4()
    {
        // Constructor
    }

    public AExpOp3ExpExpLogica4(
        @SuppressWarnings("hiding") PExp _pre_,
        @SuppressWarnings("hiding") POp3 _op3_,
        @SuppressWarnings("hiding") PVarValue _varValue_)
    {
        // Constructor
        setPre(_pre_);

        setOp3(_op3_);

        setVarValue(_varValue_);

    }

    @Override
    public Object clone()
    {
        return new AExpOp3ExpExpLogica4(
            cloneNode(this._pre_),
            cloneNode(this._op3_),
            cloneNode(this._varValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpOp3ExpExpLogica4(this);
    }

    public PExp getPre()
    {
        return this._pre_;
    }

    public void setPre(PExp node)
    {
        if(this._pre_ != null)
        {
            this._pre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pre_ = node;
    }

    public POp3 getOp3()
    {
        return this._op3_;
    }

    public void setOp3(POp3 node)
    {
        if(this._op3_ != null)
        {
            this._op3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op3_ = node;
    }

    public PVarValue getVarValue()
    {
        return this._varValue_;
    }

    public void setVarValue(PVarValue node)
    {
        if(this._varValue_ != null)
        {
            this._varValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pre_)
            + toString(this._op3_)
            + toString(this._varValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pre_ == child)
        {
            this._pre_ = null;
            return;
        }

        if(this._op3_ == child)
        {
            this._op3_ = null;
            return;
        }

        if(this._varValue_ == child)
        {
            this._varValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pre_ == oldChild)
        {
            setPre((PExp) newChild);
            return;
        }

        if(this._op3_ == oldChild)
        {
            setOp3((POp3) newChild);
            return;
        }

        if(this._varValue_ == oldChild)
        {
            setVarValue((PVarValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
