/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpNeqExpExpLogica extends PExpLogica
{
    private PExp _pre_;
    private TNotEqual _notEqual_;
    private PVarValueExp _varValueExp_;

    public AExpNeqExpExpLogica()
    {
        // Constructor
    }

    public AExpNeqExpExpLogica(
        @SuppressWarnings("hiding") PExp _pre_,
        @SuppressWarnings("hiding") TNotEqual _notEqual_,
        @SuppressWarnings("hiding") PVarValueExp _varValueExp_)
    {
        // Constructor
        setPre(_pre_);

        setNotEqual(_notEqual_);

        setVarValueExp(_varValueExp_);

    }

    @Override
    public Object clone()
    {
        return new AExpNeqExpExpLogica(
            cloneNode(this._pre_),
            cloneNode(this._notEqual_),
            cloneNode(this._varValueExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpNeqExpExpLogica(this);
    }

    public PExp getPre()
    {
        return this._pre_;
    }

    public void setPre(PExp node)
    {
        if(this._pre_ != null)
        {
            this._pre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pre_ = node;
    }

    public TNotEqual getNotEqual()
    {
        return this._notEqual_;
    }

    public void setNotEqual(TNotEqual node)
    {
        if(this._notEqual_ != null)
        {
            this._notEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notEqual_ = node;
    }

    public PVarValueExp getVarValueExp()
    {
        return this._varValueExp_;
    }

    public void setVarValueExp(PVarValueExp node)
    {
        if(this._varValueExp_ != null)
        {
            this._varValueExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varValueExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pre_)
            + toString(this._notEqual_)
            + toString(this._varValueExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pre_ == child)
        {
            this._pre_ = null;
            return;
        }

        if(this._notEqual_ == child)
        {
            this._notEqual_ = null;
            return;
        }

        if(this._varValueExp_ == child)
        {
            this._varValueExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pre_ == oldChild)
        {
            setPre((PExp) newChild);
            return;
        }

        if(this._notEqual_ == oldChild)
        {
            setNotEqual((TNotEqual) newChild);
            return;
        }

        if(this._varValueExp_ == oldChild)
        {
            setVarValueExp((PVarValueExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
