/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMatrizVar extends PVar
{
    private TId _id_;
    private TLCol _lCol_;
    private TNInt _nInt_;
    private TRCol _rCol_;

    public AMatrizVar()
    {
        // Constructor
    }

    public AMatrizVar(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TLCol _lCol_,
        @SuppressWarnings("hiding") TNInt _nInt_,
        @SuppressWarnings("hiding") TRCol _rCol_)
    {
        // Constructor
        setId(_id_);

        setLCol(_lCol_);

        setNInt(_nInt_);

        setRCol(_rCol_);

    }

    @Override
    public Object clone()
    {
        return new AMatrizVar(
            cloneNode(this._id_),
            cloneNode(this._lCol_),
            cloneNode(this._nInt_),
            cloneNode(this._rCol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatrizVar(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TLCol getLCol()
    {
        return this._lCol_;
    }

    public void setLCol(TLCol node)
    {
        if(this._lCol_ != null)
        {
            this._lCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCol_ = node;
    }

    public TNInt getNInt()
    {
        return this._nInt_;
    }

    public void setNInt(TNInt node)
    {
        if(this._nInt_ != null)
        {
            this._nInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nInt_ = node;
    }

    public TRCol getRCol()
    {
        return this._rCol_;
    }

    public void setRCol(TRCol node)
    {
        if(this._rCol_ != null)
        {
            this._rCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rCol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._lCol_)
            + toString(this._nInt_)
            + toString(this._rCol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._lCol_ == child)
        {
            this._lCol_ = null;
            return;
        }

        if(this._nInt_ == child)
        {
            this._nInt_ = null;
            return;
        }

        if(this._rCol_ == child)
        {
            this._rCol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._lCol_ == oldChild)
        {
            setLCol((TLCol) newChild);
            return;
        }

        if(this._nInt_ == oldChild)
        {
            setNInt((TNInt) newChild);
            return;
        }

        if(this._rCol_ == oldChild)
        {
            setRCol((TRCol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
