/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMenorigualExpLogica extends PExpLogica
{
    private PExp _pre_;
    private TMenorEqual _menorEqual_;
    private PExp _pos_;

    public AMenorigualExpLogica()
    {
        // Constructor
    }

    public AMenorigualExpLogica(
        @SuppressWarnings("hiding") PExp _pre_,
        @SuppressWarnings("hiding") TMenorEqual _menorEqual_,
        @SuppressWarnings("hiding") PExp _pos_)
    {
        // Constructor
        setPre(_pre_);

        setMenorEqual(_menorEqual_);

        setPos(_pos_);

    }

    @Override
    public Object clone()
    {
        return new AMenorigualExpLogica(
            cloneNode(this._pre_),
            cloneNode(this._menorEqual_),
            cloneNode(this._pos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorigualExpLogica(this);
    }

    public PExp getPre()
    {
        return this._pre_;
    }

    public void setPre(PExp node)
    {
        if(this._pre_ != null)
        {
            this._pre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pre_ = node;
    }

    public TMenorEqual getMenorEqual()
    {
        return this._menorEqual_;
    }

    public void setMenorEqual(TMenorEqual node)
    {
        if(this._menorEqual_ != null)
        {
            this._menorEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorEqual_ = node;
    }

    public PExp getPos()
    {
        return this._pos_;
    }

    public void setPos(PExp node)
    {
        if(this._pos_ != null)
        {
            this._pos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pre_)
            + toString(this._menorEqual_)
            + toString(this._pos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pre_ == child)
        {
            this._pre_ = null;
            return;
        }

        if(this._menorEqual_ == child)
        {
            this._menorEqual_ = null;
            return;
        }

        if(this._pos_ == child)
        {
            this._pos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pre_ == oldChild)
        {
            setPre((PExp) newChild);
            return;
        }

        if(this._menorEqual_ == oldChild)
        {
            setMenorEqual((TMenorEqual) newChild);
            return;
        }

        if(this._pos_ == oldChild)
        {
            setPos((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
