/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APassoStep extends PStep
{
    private TPass _pass_;
    private TNInt _nInt_;

    public APassoStep()
    {
        // Constructor
    }

    public APassoStep(
        @SuppressWarnings("hiding") TPass _pass_,
        @SuppressWarnings("hiding") TNInt _nInt_)
    {
        // Constructor
        setPass(_pass_);

        setNInt(_nInt_);

    }

    @Override
    public Object clone()
    {
        return new APassoStep(
            cloneNode(this._pass_),
            cloneNode(this._nInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPassoStep(this);
    }

    public TPass getPass()
    {
        return this._pass_;
    }

    public void setPass(TPass node)
    {
        if(this._pass_ != null)
        {
            this._pass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pass_ = node;
    }

    public TNInt getNInt()
    {
        return this._nInt_;
    }

    public void setNInt(TNInt node)
    {
        if(this._nInt_ != null)
        {
            this._nInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pass_)
            + toString(this._nInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pass_ == child)
        {
            this._pass_ = null;
            return;
        }

        if(this._nInt_ == child)
        {
            this._nInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pass_ == oldChild)
        {
            setPass((TPass) newChild);
            return;
        }

        if(this._nInt_ == oldChild)
        {
            setNInt((TNInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
