/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AVariValExpExp extends PExp
{
    private PVarValueExp _varValueExp_;

    public AVariValExpExp()
    {
        // Constructor
    }

    public AVariValExpExp(
        @SuppressWarnings("hiding") PVarValueExp _varValueExp_)
    {
        // Constructor
        setVarValueExp(_varValueExp_);

    }

    @Override
    public Object clone()
    {
        return new AVariValExpExp(
            cloneNode(this._varValueExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariValExpExp(this);
    }

    public PVarValueExp getVarValueExp()
    {
        return this._varValueExp_;
    }

    public void setVarValueExp(PVarValueExp node)
    {
        if(this._varValueExp_ != null)
        {
            this._varValueExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varValueExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varValueExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varValueExp_ == child)
        {
            this._varValueExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varValueExp_ == oldChild)
        {
            setVarValueExp((PVarValueExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
