/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AWriteLogComando extends PComando
{
    private final LinkedList<PExprComma> _exprComma_ = new LinkedList<PExprComma>();
    private PExpLogica _expLogica_;

    public AWriteLogComando()
    {
        // Constructor
    }

    public AWriteLogComando(
        @SuppressWarnings("hiding") List<?> _exprComma_,
        @SuppressWarnings("hiding") PExpLogica _expLogica_)
    {
        // Constructor
        setExprComma(_exprComma_);

        setExpLogica(_expLogica_);

    }

    @Override
    public Object clone()
    {
        return new AWriteLogComando(
            cloneList(this._exprComma_),
            cloneNode(this._expLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWriteLogComando(this);
    }

    public LinkedList<PExprComma> getExprComma()
    {
        return this._exprComma_;
    }

    public void setExprComma(List<?> list)
    {
        for(PExprComma e : this._exprComma_)
        {
            e.parent(null);
        }
        this._exprComma_.clear();

        for(Object obj_e : list)
        {
            PExprComma e = (PExprComma) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._exprComma_.add(e);
        }
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprComma_)
            + toString(this._expLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprComma_.remove(child))
        {
            return;
        }

        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExprComma> i = this._exprComma_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExprComma) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
