/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TCase extends Token
{
    public TCase()
    {
        super.setText("caso");
    }

    public TCase(int line, int pos)
    {
        super.setText("caso");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCase(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCase(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCase text.");
    }
}
