/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAStartPrograma(AStartPrograma node)
    {
        defaultIn(node);
    }

    public void outAStartPrograma(AStartPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStartPrograma(AStartPrograma node)
    {
        inAStartPrograma(node);
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PDeclaracao> copy = new ArrayList<PDeclaracao>(node.getDeclaracao());
            Collections.reverse(copy);
            for(PDeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getBegin() != null)
        {
            node.getBegin().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        outAStartPrograma(node);
    }

    public void inAStringValor(AStringValor node)
    {
        defaultIn(node);
    }

    public void outAStringValor(AStringValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringValor(AStringValor node)
    {
        inAStringValor(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringValor(node);
    }

    public void inAIntegerValor(AIntegerValor node)
    {
        defaultIn(node);
    }

    public void outAIntegerValor(AIntegerValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntegerValor(AIntegerValor node)
    {
        inAIntegerValor(node);
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        outAIntegerValor(node);
    }

    public void inARealValor(ARealValor node)
    {
        defaultIn(node);
    }

    public void outARealValor(ARealValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealValor(ARealValor node)
    {
        inARealValor(node);
        if(node.getNReal() != null)
        {
            node.getNReal().apply(this);
        }
        outARealValor(node);
    }

    public void inARealTipo(ARealTipo node)
    {
        defaultIn(node);
    }

    public void outARealTipo(ARealTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealTipo(ARealTipo node)
    {
        inARealTipo(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outARealTipo(node);
    }

    public void inAIntegerTipo(AIntegerTipo node)
    {
        defaultIn(node);
    }

    public void outAIntegerTipo(AIntegerTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntegerTipo(AIntegerTipo node)
    {
        inAIntegerTipo(node);
        if(node.getInteger() != null)
        {
            node.getInteger().apply(this);
        }
        outAIntegerTipo(node);
    }

    public void inACharTipo(ACharTipo node)
    {
        defaultIn(node);
    }

    public void outACharTipo(ACharTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACharTipo(ACharTipo node)
    {
        inACharTipo(node);
        if(node.getCharacter() != null)
        {
            node.getCharacter().apply(this);
        }
        outACharTipo(node);
    }

    public void inAIdVar(AIdVar node)
    {
        defaultIn(node);
    }

    public void outAIdVar(AIdVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdVar(AIdVar node)
    {
        inAIdVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdVar(node);
    }

    public void inAMatrixVar(AMatrixVar node)
    {
        defaultIn(node);
    }

    public void outAMatrixVar(AMatrixVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMatrixVar(AMatrixVar node)
    {
        inAMatrixVar(node);
        if(node.getRBra() != null)
        {
            node.getRBra().apply(this);
        }
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        if(node.getLBra() != null)
        {
            node.getLBra().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAMatrixVar(node);
    }

    public void inAVarComVariavelComma(AVarComVariavelComma node)
    {
        defaultIn(node);
    }

    public void outAVarComVariavelComma(AVarComVariavelComma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarComVariavelComma(AVarComVariavelComma node)
    {
        inAVarComVariavelComma(node);
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVarComVariavelComma(node);
    }

    public void inAVariableDeclaracao(AVariableDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAVariableDeclaracao(AVariableDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariableDeclaracao(AVariableDeclaracao node)
    {
        inAVariableDeclaracao(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        {
            List<PVariavelComma> copy = new ArrayList<PVariavelComma>(node.getVariavelComma());
            Collections.reverse(copy);
            for(PVariavelComma e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAVariableDeclaracao(node);
    }

    public void inAConstantDeclaracao(AConstantDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAConstantDeclaracao(AConstantDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstantDeclaracao(AConstantDeclaracao node)
    {
        inAConstantDeclaracao(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getConstant() != null)
        {
            node.getConstant().apply(this);
        }
        outAConstantDeclaracao(node);
    }

    public void inAExpComExprComma(AExpComExprComma node)
    {
        defaultIn(node);
    }

    public void outAExpComExprComma(AExpComExprComma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpComExprComma(AExpComExprComma node)
    {
        inAExpComExprComma(node);
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAExpComExprComma(node);
    }

    public void inAExplogComExprComma(AExplogComExprComma node)
    {
        defaultIn(node);
    }

    public void outAExplogComExprComma(AExplogComExprComma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExplogComExprComma(AExplogComExprComma node)
    {
        inAExplogComExprComma(node);
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        outAExplogComExprComma(node);
    }

    public void inAElseOpcOpcionalElse(AElseOpcOpcionalElse node)
    {
        defaultIn(node);
    }

    public void outAElseOpcOpcionalElse(AElseOpcOpcionalElse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseOpcOpcionalElse(AElseOpcOpcionalElse node)
    {
        inAElseOpcOpcionalElse(node);
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseOpcOpcionalElse(node);
    }

    public void inACaseStarCaseEstrela(ACaseStarCaseEstrela node)
    {
        defaultIn(node);
    }

    public void outACaseStarCaseEstrela(ACaseStarCaseEstrela node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACaseStarCaseEstrela(ACaseStarCaseEstrela node)
    {
        inACaseStarCaseEstrela(node);
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        outACaseStarCaseEstrela(node);
    }

    public void inAElseColonOpcOpcionalElseColon(AElseColonOpcOpcionalElseColon node)
    {
        defaultIn(node);
    }

    public void outAElseColonOpcOpcionalElseColon(AElseColonOpcOpcionalElseColon node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseColonOpcOpcionalElseColon(AElseColonOpcOpcionalElseColon node)
    {
        inAElseColonOpcOpcionalElseColon(node);
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseColonOpcOpcionalElseColon(node);
    }

    public void inAValueVarValue(AValueVarValue node)
    {
        defaultIn(node);
    }

    public void outAValueVarValue(AValueVarValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValueVarValue(AValueVarValue node)
    {
        inAValueVarValue(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        outAValueVarValue(node);
    }

    public void inAVariableVarValue(AVariableVarValue node)
    {
        defaultIn(node);
    }

    public void outAVariableVarValue(AVariableVarValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariableVarValue(AVariableVarValue node)
    {
        inAVariableVarValue(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVariableVarValue(node);
    }

    public void inAExpPlusTerExp(AExpPlusTerExp node)
    {
        defaultIn(node);
    }

    public void outAExpPlusTerExp(AExpPlusTerExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpPlusTerExp(AExpPlusTerExp node)
    {
        inAExpPlusTerExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAExpPlusTerExp(node);
    }

    public void inAExpMinusTerExp(AExpMinusTerExp node)
    {
        defaultIn(node);
    }

    public void outAExpMinusTerExp(AExpMinusTerExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpMinusTerExp(AExpMinusTerExp node)
    {
        inAExpMinusTerExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAExpMinusTerExp(node);
    }

    public void inATerExp(ATerExp node)
    {
        defaultIn(node);
    }

    public void outATerExp(ATerExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATerExp(ATerExp node)
    {
        inATerExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATerExp(node);
    }

    public void inATerMultFatTermo(ATerMultFatTermo node)
    {
        defaultIn(node);
    }

    public void outATerMultFatTermo(ATerMultFatTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATerMultFatTermo(ATerMultFatTermo node)
    {
        inATerMultFatTermo(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATerMultFatTermo(node);
    }

    public void inATerDivFatTermo(ATerDivFatTermo node)
    {
        defaultIn(node);
    }

    public void outATerDivFatTermo(ATerDivFatTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATerDivFatTermo(ATerDivFatTermo node)
    {
        inATerDivFatTermo(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATerDivFatTermo(node);
    }

    public void inAFatTermo(AFatTermo node)
    {
        defaultIn(node);
    }

    public void outAFatTermo(AFatTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFatTermo(AFatTermo node)
    {
        inAFatTermo(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAFatTermo(node);
    }

    public void inALExpRFator(ALExpRFator node)
    {
        defaultIn(node);
    }

    public void outALExpRFator(ALExpRFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALExpRFator(ALExpRFator node)
    {
        inALExpRFator(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outALExpRFator(node);
    }

    public void inAVariValFator(AVariValFator node)
    {
        defaultIn(node);
    }

    public void outAVariValFator(AVariValFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariValFator(AVariValFator node)
    {
        inAVariValFator(node);
        if(node.getVarValue() != null)
        {
            node.getVarValue().apply(this);
        }
        outAVariValFator(node);
    }

    public void inAOp31Op3(AOp31Op3 node)
    {
        defaultIn(node);
    }

    public void outAOp31Op3(AOp31Op3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOp31Op3(AOp31Op3 node)
    {
        inAOp31Op3(node);
        if(node.getLessEq() != null)
        {
            node.getLessEq().apply(this);
        }
        outAOp31Op3(node);
    }

    public void inAOp32Op3(AOp32Op3 node)
    {
        defaultIn(node);
    }

    public void outAOp32Op3(AOp32Op3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOp32Op3(AOp32Op3 node)
    {
        inAOp32Op3(node);
        if(node.getLess() != null)
        {
            node.getLess().apply(this);
        }
        outAOp32Op3(node);
    }

    public void inAOp33Op3(AOp33Op3 node)
    {
        defaultIn(node);
    }

    public void outAOp33Op3(AOp33Op3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOp33Op3(AOp33Op3 node)
    {
        inAOp33Op3(node);
        if(node.getGreaterEq() != null)
        {
            node.getGreaterEq().apply(this);
        }
        outAOp33Op3(node);
    }

    public void inAOp34Op3(AOp34Op3 node)
    {
        defaultIn(node);
    }

    public void outAOp34Op3(AOp34Op3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOp34Op3(AOp34Op3 node)
    {
        inAOp34Op3(node);
        if(node.getGreater() != null)
        {
            node.getGreater().apply(this);
        }
        outAOp34Op3(node);
    }

    public void inAOp41Op4(AOp41Op4 node)
    {
        defaultIn(node);
    }

    public void outAOp41Op4(AOp41Op4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOp41Op4(AOp41Op4 node)
    {
        inAOp41Op4(node);
        if(node.getEqual() != null)
        {
            node.getEqual().apply(this);
        }
        outAOp41Op4(node);
    }

    public void inAOp42Op4(AOp42Op4 node)
    {
        defaultIn(node);
    }

    public void outAOp42Op4(AOp42Op4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOp42Op4(AOp42Op4 node)
    {
        inAOp42Op4(node);
        if(node.getNotEqual() != null)
        {
            node.getNotEqual().apply(this);
        }
        outAOp42Op4(node);
    }

    public void inAOrExpExpLogica(AOrExpExpLogica node)
    {
        defaultIn(node);
    }

    public void outAOrExpExpLogica(AOrExpExpLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExpExpLogica(AOrExpExpLogica node)
    {
        inAOrExpExpLogica(node);
        if(node.getPos() != null)
        {
            node.getPos().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getPre() != null)
        {
            node.getPre().apply(this);
        }
        outAOrExpExpLogica(node);
    }

    public void inAExpLogica(AExpLogica node)
    {
        defaultIn(node);
    }

    public void outAExpLogica(AExpLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpLogica(AExpLogica node)
    {
        inAExpLogica(node);
        if(node.getExpLogica2() != null)
        {
            node.getExpLogica2().apply(this);
        }
        outAExpLogica(node);
    }

    public void inAXorExpExpLogica2(AXorExpExpLogica2 node)
    {
        defaultIn(node);
    }

    public void outAXorExpExpLogica2(AXorExpExpLogica2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAXorExpExpLogica2(AXorExpExpLogica2 node)
    {
        inAXorExpExpLogica2(node);
        if(node.getPos() != null)
        {
            node.getPos().apply(this);
        }
        if(node.getXor() != null)
        {
            node.getXor().apply(this);
        }
        if(node.getPre() != null)
        {
            node.getPre().apply(this);
        }
        outAXorExpExpLogica2(node);
    }

    public void inAExpLogica2(AExpLogica2 node)
    {
        defaultIn(node);
    }

    public void outAExpLogica2(AExpLogica2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpLogica2(AExpLogica2 node)
    {
        inAExpLogica2(node);
        if(node.getExpLogica3() != null)
        {
            node.getExpLogica3().apply(this);
        }
        outAExpLogica2(node);
    }

    public void inAAndExpExpLogica3(AAndExpExpLogica3 node)
    {
        defaultIn(node);
    }

    public void outAAndExpExpLogica3(AAndExpExpLogica3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExpExpLogica3(AAndExpExpLogica3 node)
    {
        inAAndExpExpLogica3(node);
        if(node.getPos() != null)
        {
            node.getPos().apply(this);
        }
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getPre() != null)
        {
            node.getPre().apply(this);
        }
        outAAndExpExpLogica3(node);
    }

    public void inAExpLogica3(AExpLogica3 node)
    {
        defaultIn(node);
    }

    public void outAExpLogica3(AExpLogica3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpLogica3(AExpLogica3 node)
    {
        inAExpLogica3(node);
        if(node.getExpLogica4() != null)
        {
            node.getExpLogica4().apply(this);
        }
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        outAExpLogica3(node);
    }

    public void inAExpOp4ExpExpLogica4(AExpOp4ExpExpLogica4 node)
    {
        defaultIn(node);
    }

    public void outAExpOp4ExpExpLogica4(AExpOp4ExpExpLogica4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpOp4ExpExpLogica4(AExpOp4ExpExpLogica4 node)
    {
        inAExpOp4ExpExpLogica4(node);
        if(node.getVarValue() != null)
        {
            node.getVarValue().apply(this);
        }
        if(node.getOp4() != null)
        {
            node.getOp4().apply(this);
        }
        if(node.getPre() != null)
        {
            node.getPre().apply(this);
        }
        outAExpOp4ExpExpLogica4(node);
    }

    public void inAExpOp3ExpExpLogica4(AExpOp3ExpExpLogica4 node)
    {
        defaultIn(node);
    }

    public void outAExpOp3ExpExpLogica4(AExpOp3ExpExpLogica4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpOp3ExpExpLogica4(AExpOp3ExpExpLogica4 node)
    {
        inAExpOp3ExpExpLogica4(node);
        if(node.getVarValue() != null)
        {
            node.getVarValue().apply(this);
        }
        if(node.getOp3() != null)
        {
            node.getOp3().apply(this);
        }
        if(node.getPre() != null)
        {
            node.getPre().apply(this);
        }
        outAExpOp3ExpExpLogica4(node);
    }

    public void inAParExpExpLogica4(AParExpExpLogica4 node)
    {
        defaultIn(node);
    }

    public void outAParExpExpLogica4(AParExpExpLogica4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParExpExpLogica4(AParExpExpLogica4 node)
    {
        inAParExpExpLogica4(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAParExpExpLogica4(node);
    }

    public void inAPassoStep(APassoStep node)
    {
        defaultIn(node);
    }

    public void outAPassoStep(APassoStep node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPassoStep(APassoStep node)
    {
        inAPassoStep(node);
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        if(node.getPass() != null)
        {
            node.getPass().apply(this);
        }
        outAPassoStep(node);
    }

    public void inAAtribComando(AAtribComando node)
    {
        defaultIn(node);
    }

    public void outAAtribComando(AAtribComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribComando(AAtribComando node)
    {
        inAAtribComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getIs() != null)
        {
            node.getIs().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAAtribComando(node);
    }

    public void inAAtribLogComando(AAtribLogComando node)
    {
        defaultIn(node);
    }

    public void outAAtribLogComando(AAtribLogComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribLogComando(AAtribLogComando node)
    {
        inAAtribLogComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getIs() != null)
        {
            node.getIs().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAAtribLogComando(node);
    }

    public void inAReadComando(AReadComando node)
    {
        defaultIn(node);
    }

    public void outAReadComando(AReadComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReadComando(AReadComando node)
    {
        inAReadComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        {
            List<PVariavelComma> copy = new ArrayList<PVariavelComma>(node.getVariavelComma());
            Collections.reverse(copy);
            for(PVariavelComma e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getRead() != null)
        {
            node.getRead().apply(this);
        }
        outAReadComando(node);
    }

    public void inAWriteComando(AWriteComando node)
    {
        defaultIn(node);
    }

    public void outAWriteComando(AWriteComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWriteComando(AWriteComando node)
    {
        inAWriteComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        {
            List<PExprComma> copy = new ArrayList<PExprComma>(node.getExprComma());
            Collections.reverse(copy);
            for(PExprComma e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getWrite() != null)
        {
            node.getWrite().apply(this);
        }
        outAWriteComando(node);
    }

    public void inAIfComando(AIfComando node)
    {
        defaultIn(node);
    }

    public void outAIfComando(AIfComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfComando(AIfComando node)
    {
        inAIfComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getEndIf() != null)
        {
            node.getEndIf().apply(this);
        }
        if(node.getOpcionalElse() != null)
        {
            node.getOpcionalElse().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getThen() != null)
        {
            node.getThen().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAIfComando(node);
    }

    public void inAEvaluateComando(AEvaluateComando node)
    {
        defaultIn(node);
    }

    public void outAEvaluateComando(AEvaluateComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEvaluateComando(AEvaluateComando node)
    {
        inAEvaluateComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getEndE() != null)
        {
            node.getEndE().apply(this);
        }
        if(node.getOpcionalElseColon() != null)
        {
            node.getOpcionalElseColon().apply(this);
        }
        {
            List<PCaseEstrela> copy = new ArrayList<PCaseEstrela>(node.getCaseEstrela());
            Collections.reverse(copy);
            for(PCaseEstrela e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getEvaluate() != null)
        {
            node.getEvaluate().apply(this);
        }
        outAEvaluateComando(node);
    }

    public void inAEvaluateLogComando(AEvaluateLogComando node)
    {
        defaultIn(node);
    }

    public void outAEvaluateLogComando(AEvaluateLogComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEvaluateLogComando(AEvaluateLogComando node)
    {
        inAEvaluateLogComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getEndE() != null)
        {
            node.getEndE().apply(this);
        }
        if(node.getOpcionalElseColon() != null)
        {
            node.getOpcionalElseColon().apply(this);
        }
        {
            List<PCaseEstrela> copy = new ArrayList<PCaseEstrela>(node.getCaseEstrela());
            Collections.reverse(copy);
            for(PCaseEstrela e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getEvaluate() != null)
        {
            node.getEvaluate().apply(this);
        }
        outAEvaluateLogComando(node);
    }

    public void inAWhileComando(AWhileComando node)
    {
        defaultIn(node);
    }

    public void outAWhileComando(AWhileComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileComando(AWhileComando node)
    {
        inAWhileComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getEndW() != null)
        {
            node.getEndW().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        outAWhileComando(node);
    }

    public void inARepeatComando(ARepeatComando node)
    {
        defaultIn(node);
    }

    public void outARepeatComando(ARepeatComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARepeatComando(ARepeatComando node)
    {
        inARepeatComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getUntil() != null)
        {
            node.getUntil().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRepeat() != null)
        {
            node.getRepeat().apply(this);
        }
        outARepeatComando(node);
    }

    public void inAForOneComando(AForOneComando node)
    {
        defaultIn(node);
    }

    public void outAForOneComando(AForOneComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForOneComando(AForOneComando node)
    {
        inAForOneComando(node);
        if(node.getSemiC() != null)
        {
            node.getSemiC().apply(this);
        }
        if(node.getEndF() != null)
        {
            node.getEndF().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getStop() != null)
        {
            node.getStop().apply(this);
        }
        if(node.getUntil() != null)
        {
            node.getUntil().apply(this);
        }
        if(node.getStep() != null)
        {
            node.getStep().apply(this);
        }
        if(node.getStart() != null)
        {
            node.getStart().apply(this);
        }
        if(node.getFrom() != null)
        {
            node.getFrom().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getFor() != null)
        {
            node.getFor().apply(this);
        }
        outAForOneComando(node);
    }
}
